#SQl queries for PLaystore_app & Reviews

#Question 1 - apps have the highest rating in the given available dataset?
select App from apps where Rating = 5;
#select Count(*) from apps where Rating = 5;

#Question 2 - What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
select App, Installs, Reviews from apps where Rating = 5 order by Reviews desc;

#Question 3 - Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
select App, Category, Installs, Reviews from apps where Rating = 5 order by Reviews desc limit 1;

#Question 4 - What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
select Sum(Installs * Price) as Revenue from apps;

#Question 5 - Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
select Category, Sum(Installs) as total_installs from apps group by Category order by total_installs desc limit 1;

#Question 6 - Which Genre has the most number of published apps?
select Genres, Count(*) as total from apps group by Genres order by total desc limit 1;

#Question 7 - Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
select distinct App, Installs from apps where Category = 'Game' order by Installs desc;

#Question 8 - Provide the list of apps that can work on android version 4.0.3 and UP.
Select App from apps where 'Android Ver'>='4.0.3';

#Question 9 - How many apps from the given data set are free? Also, provide the number of paid apps.
Select Count(*) as Total_Free_apps from apps where Type='Free';
Select Count(*) as Total_Free_apps from apps where Type='Paid';

#Question 10 - Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
Select App, Reviews from apps where Category='Dating' or Genres='Dating' order by Reviews Desc limit 1;

#Question 11 - Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app 10 best foods for you and compare them.
select count(*) from reviews where App ='10 Best Foods for You' and Sentiment_Polarity>0;
select count(*) from reviews where App ='10 Best Foods for You' and Sentiment_Polarity<0;


#Question 12 - Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
select Translated_Review from reviews where App ='ASUS SuperNote' and Sentiment_Polarity=1 and Sentiment_Subjectivity = 1;

#Question 13 - Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 
select Translated_Review from reviews where App ='Abs Training-Burn belly fat ' and Sentiment_Polarity = 0;

#Question 14 - Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity
select Translated_Review,Sentiment_Polarity,Sentiment_Subjectivity from reviews where  App='Adobe Acrobat Reader ' and Sentiment_Polarity < 0;
